from selenium.webdriver.common.by import By

terms_link_loc = (By.LINK_TEXT, 'Terms and Conditions')
standard_terms_loc = (By.TAG_NAME, 'h1')
price_text_loc = (By.CSS_SELECTOR, 'span.oe_currency_value')
plus_button_loc = (By.CSS_SELECTOR, 'i.fa.fa-plus')
minus_button_loc = (By.CSS_SELECTOR, 'i.fa.fa-minus')
add_cart_button_loc = (By.ID, 'add_to_cart_wrap')
alert = (By.CSS_SELECTOR, 'div.toast.show')
view_cart_loc = (By.CSS_SELECTOR, "a.btn.btn-primary[href='/shop/cart']")
cart_price_text_loc = (By.CSS_SELECTOR, 'span.oe_currency_value')
quantity_input_loc = (By.CSS_SELECTOR, 'input.js_quantity')
input_promo_loc = (By.NAME, 'promo')
button_apply_loc = (By.CLASS_NAME, 'btn-secondary')
alert_element_loc = (By.CSS_SELECTOR, "div.alert.alert-danger.text-start[role='alert']")
button_checkout_loc = (By.NAME, 'website_sale_main_button')
button_continue_checkout_loc = (By.CLASS_NAME, 'a-submit-disable')
note_empty_fields_loc = (By.TAG_NAME, 'h5')
select_currency_loc = (By.CSS_SELECTOR, 'a.dropdown-toggle.btn.btn-light')
eur_option_loc = (By.XPATH, "//a[contains(@href, '/shop/change_pricelist/3')]")
price_block_loc = (By.CSS_SELECTOR, 'div.product_price')
plus_in_cart_loc = (By.CSS_SELECTOR, 'a[aria-label="Add one"] i.fa-minus')
minus_in_cart_loc = (By.CSS_SELECTOR, 'a[aria-label="Remove one"] i.fa-minus')
